VEuPathDB/CoreUI

- package.json
- src/components/containers/ExpandablePanel/index.tsx
* Long subtitles could previously go right to the end of the component and that didn't look very nice.
> RC: 0.11.3 - Add a right margin to subtitles in `ExpandablePanel`.

- .storybook/preview.js
- package.json
- src/components/grids/DataGrid/index.tsx
- src/stories/grids/DataGrid.stories.tsx
- yarn.lock
Workaround for the issue reported here
https://github.com/TanStack/react-table/issues/2459#issuecomment-851523333
When you add `isSelected: true` to row items that you want to be selected already, it wasn't working properly, but now it is.
> Handle pre-selected row items properly; storybook actions console log addon

- src/components/grids/DataGrid/stylePresets.ts
closes #72 
This PR adjusts the data cell text color for the "mesa" preset
Before:
After:
> Use a darker text color for the "mesa" preset

- src/components/grids/TabbedDisplay/index.tsx
This refactored version is being used in the work for [this PR](https://github.com/VEuPathDB/ApiCommonWebsite/pull/69).
> Refactor TabbedDisplay to remove internal state

- src/components/banners/Banner.tsx
- src/components/notifications/SnackbarProvider.tsx
- src/definitions/colors.ts
This PR adds the three alert colors. 
The goal here is to simply add the colors and swap them into `Banner` and `Snackbar` where appropriate. I'm leaving other related design changes to these components to a separate PR.
> add theme-agnostic colors

- package.json
- src/components/grids/TabbedDisplay/index.tsx
There was feedback on an implementation of `TabbedDisplay` that requested increasing the font size of the tab labels. As a result, the `styleOverrides` have been adjusted to allow for such alterations. Also, the `H6` component that was used for the tab label has been replaced with a more semantically-appropriate `<span>` element.
> Add styleOverrides for TabbedDisplay's tab labels

- src/components/grids/DataGrid/stylePresets.ts
There has been [recent discussion](https://github.com/VEuPathDB/web-eda/pull/1263#event-7059013173) about whether or not we should be transforming text on the client side. The general consensus seems to be: no, we should not.
Thus, I'm removing the `textTransform` default style from the `DataGrid` component's column headers.
> Remove textTransform from DataGrid's headerCells default CSS

- .github/workflows/npm-publish.yml
There are [some peculiarities](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) around how the workflow for package releases are generated in regards to `published` versus `created`.
Hopefully this will resolve those peculiarities.
> Change npm release type from created to published

- .github/workflows/npm-publish.yml
Current workflow that publishes the `npm` package is using `npm` (shown below) whereas all other client repos use `yarn`.
```yml
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
with:
node-version: 14
- run: npm install
- run: npm run build
```
> Use yarn instead of npm in GitHub workflow

- package.json
- src/components/inputs/SearchBox/SearchBox.tsx
- src/components/inputs/SelectList.tsx
- src/components/inputs/checkboxes/CheckboxTree/CheckboxTree.tsx
- src/components/inputs/checkboxes/CheckboxTree/CheckboxTreeNode.tsx
These changes were brought on while implementing the new `Select*` and `Checkbox*` components in the following `web-eda` contexts:
1. the variable selectors in the viz tab
2. the browse and subset `CheckboxTree`
3. the download modal's `CheckboxTree`
> Tweak new CoreUI components during implementation

- package.json
- src/components/icons/ArrowDown.tsx
- src/components/icons/ArrowRight.tsx
- src/components/icons/index.tsx
- src/stories/typography/Icons.stories.tsx
This PR adds two new icons to be used in the `CheckboxTree` expand/collapse toggles: `ArrowDown` and `ArrowRight`. During this work, I also added all icons to the `Typography/Icons` story.
> Add ArrowDown and ArrowRight icons and add all icons to story

- package.json
- src/components/icons/ArrowDown.tsx
Fixes an error in which props weren't spread into the `ArrowDown` icon's SVG.
> Spread props into ArrowDown icon

- package.json
- src/components/inputs/SelectList.tsx
- src/components/inputs/SingleSelect.tsx
- src/components/inputs/checkboxes/CheckboxList.tsx
In response to [feedback for the work in implementing `SingleSelect` in mbio's `alphaDiv` and `abundance` plugin configs](https://github.com/VEuPathDB/web-eda/pull/1394#pullrequestreview-1141785757).
By changing the type of the `value` prop of `SingleSelect` to be `any`, we greatly simplify this particular implementation by obviating the existing JSON stringifying and parsing.
> Use generics in value prop type in SelectList, CheckboxList, and SingleSelect

- package.json
- src/components/widgets/Toggle.tsx
Closes https://github.com/VEuPathDB/EdaNewIssues/issues/446
Follow-up work could include adding the `font-family` to the [`UIThemeProvider` in `web-eda`](https://github.com/VEuPathDB/web-eda/blob/0a75053e66bb5f9bca3a8470da691a335235a011/src/index.tsx#L122-L129) instead of hardcoding the `font-family` for now.
> Style toggle label according to enabled/disabled state

- package.json
- src/components/banners/Banner.tsx
- src/stories/notifications/Banners.stories.tsx
To address https://github.com/VEuPathDB/web-eda/issues/1423, Banner component needs to have show more/less like functionality. Also made a story to test it, with toggle button to enable/disable show more/less with ease, and added onClose function at the story to test. 
I have added @chowington and @jernestmyers as you are actively updating this CoreUI. Any suggestion on the name of props would be welcome 😃 
Here are screenshots:
- without showMore: typical message is shown
- with showMore: a link is provided to press (used Why? as the link)
- with showMore and pressing the showMore link: will show additional message and show less like link (used Read less)
> add show more function to Banner

- package.json
- src/components/grids/TabbedDisplay/index.tsx
This is necessary to address https://github.com/VEuPathDB/web-eda/issues/998. I noticed that Jeremy used DARKEST_GRAY which is gray[900] for unifying text colors for log scale, etc. (https://github.com/VEuPathDB/web-components/pull/402) so I used the same color here. 
- A screenshot can be found in https://github.com/VEuPathDB/web-eda/pull/1461#issue-1435243262
> change text colors

- package.json
- src/components/inputs/SelectTree/SelectTree.tsx
- src/components/inputs/checkboxes/CheckboxTree/CheckboxTree.tsx
- src/components/inputs/checkboxes/CheckboxTree/CheckboxTreeNode.tsx
Works towards performance improvements in `CheckboxTree`, as described in the first task of #127.
> Replace CheckboxTreeNode's inline styles with CSS selectors

- package.json
- src/components/inputs/checkboxes/CheckboxList.tsx
This is a trivial change to ensure the hover effect on the links in `CheckboxList` do not inherit the global CSS style, which looks similar to a button's native hover effect.
Came to my attention while working on https://github.com/VEuPathDB/WDKClient/pull/264
> Override eupathdb-Buttons class CSS in CheckboxList

- package.json
- src/components/banners/Banner.tsx
- src/stories/notifications/Banners.stories.tsx
Following the request to narrow down the banner size from https://github.com/VEuPathDB/web-eda/issues/1502, I have added margin, padding, and font size props for use. Perhaps there may be better naming
> add banner props to control spacing

- package.json
- src/components/inputs/checkboxes/CheckboxTree/CheckboxTree.tsx
- src/components/inputs/checkboxes/CheckboxTree/CheckboxTreeNode.tsx
This PR adds a few more performance improvements to CheckboxTree.
Ensure hook dependencies are as succinct as possible, and ensure props are memoized where possible.
> CheckboxTree performance improvements

- package.json
- src/components/inputs/SelectTree/SelectTree.tsx
- src/components/inputs/checkboxes/CheckboxTree/CheckboxTree.tsx
- src/definitions/animations.ts
Allows filtering behavior that is similar to active search behavior. Parent component can pass in a list of node ids that are used to determine a node's `isLeafVisible` state.
Relates to https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/195
> Add filteredList prop to CheckboxTree
